#! /usr/bin/env php

<?php

use Symfony\Component\Console\Application;

require 'vendor/autoload.php';

$app = new Application('Render Tabular Data', '1.0');

$app->add(new Acme\RenderCommand);

$app->run();